# Form implementation generated from reading ui file 'Chatbox.ui'
#
# Created by: PyQt6 UI code generator 6.4.2
#
# WARNING: Any manual changes made to this file will be lost when pyuic6 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt6 import QtCore, QtGui, QtWidgets
import os
import sys

class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.setWindowModality(QtCore.Qt.WindowModality.WindowModal)
        MainWindow.resize(421, 361)
        MainWindow.setMinimumSize(QtCore.QSize(421, 361))
        MainWindow.setCursor(QtGui.QCursor(QtCore.Qt.CursorShape.PointingHandCursor))
        MainWindow.setAutoFillBackground(True)
        MainWindow.setDocumentMode(True)
        MainWindow.setTabShape(QtWidgets.QTabWidget.TabShape.Rounded)
        MainWindow.setDockNestingEnabled(True)
        self.centralwidget = QtWidgets.QWidget(parent=MainWindow)
        self.centralwidget.setMinimumSize(QtCore.QSize(421, 361))
        self.centralwidget.setMaximumSize(QtCore.QSize(421, 361))
        self.centralwidget.setObjectName("centralwidget")
        self.frame = QtWidgets.QFrame(parent=self.centralwidget)
        self.frame.setGeometry(QtCore.QRect(330, 0, 101, 361))
        self.frame.setMaximumSize(QtCore.QSize(101, 361))
        self.frame.setFrameShape(QtWidgets.QFrame.Shape.StyledPanel)
        self.frame.setFrameShadow(QtWidgets.QFrame.Shadow.Raised)
        self.frame.setObjectName("frame")
        self.btnGoogle = QtWidgets.QPushButton(parent=self.frame)
        self.btnGoogle.setGeometry(QtCore.QRect(10, 62, 75, 31))
        self.btnGoogle.setMaximumSize(QtCore.QSize(75, 31))
        self.btnGoogle.setCursor(QtGui.QCursor(QtCore.Qt.CursorShape.PointingHandCursor))
        self.btnGoogle.setObjectName("btnGoogle")
        self.btnYoutube = QtWidgets.QPushButton(parent=self.frame)
        self.btnYoutube.setGeometry(QtCore.QRect(10, 130, 75, 31))
        self.btnYoutube.setMaximumSize(QtCore.QSize(75, 31))
        self.btnYoutube.setCursor(QtGui.QCursor(QtCore.Qt.CursorShape.PointingHandCursor))
        self.btnYoutube.setObjectName("btnYoutube")
        self.btnFb = QtWidgets.QPushButton(parent=self.frame)
        self.btnFb.setGeometry(QtCore.QRect(10, 200, 75, 31))
        self.btnFb.setMaximumSize(QtCore.QSize(75, 31))
        self.btnFb.setCursor(QtGui.QCursor(QtCore.Qt.CursorShape.PointingHandCursor))
        self.btnFb.setObjectName("btnFb")
        self.pushButton_5 = QtWidgets.QPushButton(parent=self.frame)
        self.pushButton_5.setGeometry(QtCore.QRect(10, 290, 75, 31))
        self.pushButton_5.setMaximumSize(QtCore.QSize(75, 31))
        self.pushButton_5.setCursor(QtGui.QCursor(QtCore.Qt.CursorShape.PointingHandCursor))
        self.pushButton_5.setObjectName("pushButton_5")
        self.listView = QtWidgets.QListView(parent=self.centralwidget)
        self.listView.setGeometry(QtCore.QRect(0, 0, 331, 331))
        self.listView.setMaximumSize(QtCore.QSize(331, 331))
        self.listView.setObjectName("listView")
        self.lineEdit = QtWidgets.QLineEdit(parent=self.centralwidget)
        self.lineEdit.setGeometry(QtCore.QRect(0, 330, 331, 31))
        self.lineEdit.setMaximumSize(QtCore.QSize(331, 31))
        self.lineEdit.setObjectName("lineEdit")
        self.btnSend = QtWidgets.QPushButton(parent=self.centralwidget)
        self.btnSend.setGeometry(QtCore.QRect(340, 330, 75, 31))
        self.btnSend.setMaximumSize(QtCore.QSize(75, 31))
        self.btnSend.setObjectName("btnSend")
        MainWindow.setCentralWidget(self.centralwidget)

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

        self.btnGoogle.clicked.connect(self.Google)
        self.pushButton_5.clicked.connect(self.Chat_gpt)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "MainWindow"))
        self.btnGoogle.setText(_translate("MainWindow", "Google"))
        self.btnYoutube.setText(_translate("MainWindow", "Youtube"))
        self.btnFb.setText(_translate("MainWindow", "Facebook"))
        self.pushButton_5.setText(_translate("MainWindow", "..."))
        self.btnSend.setText(_translate("MainWindow", "Send"))

    def Google(self):
        os.system("start https://www.google.com/search?q=" )
        self.lineEdit.clear()
    def Chat_gpt(self):
            os.system("start ./dist/main/main.exe" )
            self.lineEdit.clear()

if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    MainWindow = QtWidgets.QMainWindow()
    ui = Ui_MainWindow()
    ui.setupUi(MainWindow)
    MainWindow.show()
    sys.exit(app.exec())
